# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHfMwoovWZW6t7u1NR0afl67CdSnbSaf
"""

import pandas as pd
import numpy as np

def topsis(input_file, weights_str, impacts_str, output_file):
    df = pd.read_csv(input_file)

    df.iloc[:, 1:] = df.iloc[:, 1:].astype(float)

    weights = np.array(list(map(float, weights_str.split(","))))
    impacts = impacts_str.split(",")

    matrix = df.iloc[:, 1:].values
    norm = np.sqrt((matrix ** 2).sum(axis=0))
    normalized = matrix / norm
    weighted = normalized * weights

    ideal_best = []
    ideal_worst = []

    for i in range(len(impacts)):
        if impacts[i] == '+':
            ideal_best.append(weighted[:, i].max())
            ideal_worst.append(weighted[:, i].min())
        else:
            ideal_best.append(weighted[:, i].min())
            ideal_worst.append(weighted[:, i].max())

    ideal_best = np.array(ideal_best)
    ideal_worst = np.array(ideal_worst)

    d_pos = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    d_neg = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    score = d_neg / (d_pos + d_neg)

    df["Topsis Score"] = score
    df["Rank"] = df["Topsis Score"].rank(ascending=False).astype(int)

    df.to_csv(output_file, index=False)